export const ANIMAL_ALIASES = [
  'Quokka',
  'Wombat',
  'Echidna',
  'Platypus',
  'Koala',
  'Tasmanian Devil',
  'Eastern Grey Kangaroo',
  'Red Kangaroo',
  'Bilby',
  'Numbat',
  'Quoll',
  'Wallaby',
  'Giraffe',
  'Zebra',
  'Cheetah',
  'Lion',
  'Meerkat',
  'African Wild Dog',
  'Asian Elephant',
  'Sumatran Tiger',
  'Snow Leopard',
  'Red Panda',
  'Orangutan',
  'Sun Bear',
  'Komodo Dragon',
  'Saltwater Crocodile',
  'Wedge-tailed Eagle',
  'Little Penguin',
  'Leafy Sea Dragon',
  'Fur Seal',
];
